# Generated by Django 4.0.2 on 2022-05-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
